import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

import User from '../models/User';
import Property from '../models/Property';
import RoommateProfile from '../models/RoommateProfile';
import Review from '../models/Review';
import Enquiry from '../models/Enquiry';
import Report from '../models/Report';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/campusnest';

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log('🌱 Connected to MongoDB. Starting seed...');

  // Clear all collections
  await Promise.all([
    User.deleteMany({}),
    Property.deleteMany({}),
    RoommateProfile.deleteMany({}),
    Review.deleteMany({}),
    Enquiry.deleteMany({}),
    Report.deleteMany({}),
  ]);
  console.log('🧹 Cleared existing data');

  const hashedPassword = await bcrypt.hash('Demo@123', 12);

  // ─── USERS ──────────────────────────────────────────────
  const users = await User.insertMany([
    // Demo accounts
    {
      name: 'Priya Sharma',
      email: 'student@campusnest.demo',
      phone: '9876543210',
      password: hashedPassword,
      role: 'student',
      college: 'Gauhati University',
      isVerified: true,
      identityStatus: 'verified',
    },
    {
      name: 'Rajesh Kumar',
      email: 'owner@campusnest.demo',
      phone: '9876543211',
      password: hashedPassword,
      role: 'owner',
      isVerified: true,
      identityStatus: 'verified',
    },
    {
      name: 'Admin User',
      email: 'admin@campusnest.demo',
      phone: '9876543212',
      password: hashedPassword,
      role: 'admin',
      isVerified: true,
      identityStatus: 'verified',
    },
    // Additional students
    {
      name: 'Ankita Das',
      email: 'ankita.das@student.demo',
      phone: '9876001001',
      password: hashedPassword,
      role: 'student',
      college: 'Assam Engineering College',
      isVerified: true,
      identityStatus: 'verified',
    },
    {
      name: 'Rohan Borah',
      email: 'rohan.borah@student.demo',
      phone: '9876001002',
      password: hashedPassword,
      role: 'student',
      college: 'Cotton University',
      isVerified: false,
    },
    {
      name: 'Meenakshi Gogoi',
      email: 'meenakshi.gogoi@student.demo',
      phone: '9876001003',
      password: hashedPassword,
      role: 'student',
      college: 'Gauhati Commerce College',
      isVerified: true,
      identityStatus: 'verified',
    },
    {
      name: 'Biplab Nath',
      email: 'biplab.nath@student.demo',
      phone: '9876001004',
      password: hashedPassword,
      role: 'student',
      college: 'Assam Engineering College',
    },
    {
      name: 'Priyanka Baruah',
      email: 'priyanka.baruah@student.demo',
      phone: '9876001005',
      password: hashedPassword,
      role: 'student',
      college: 'Gauhati University',
      isVerified: true,
      identityStatus: 'verified',
    },
    // Additional owners
    {
      name: 'Suresh Deka',
      email: 'suresh.deka@owner.demo',
      phone: '9876002001',
      password: hashedPassword,
      role: 'owner',
      isVerified: true,
      identityStatus: 'verified',
    },
    {
      name: 'Mita Kalita',
      email: 'mita.kalita@owner.demo',
      phone: '9876002002',
      password: hashedPassword,
      role: 'owner',
      isVerified: true,
      identityStatus: 'pending',
    },
    {
      name: 'Binod Saikia',
      email: 'binod.saikia@owner.demo',
      phone: '9876002003',
      password: hashedPassword,
      role: 'owner',
      isVerified: false,
    },
  ]);

  const [demoStudent, demoOwner, , ankita, rohan, meenakshi, biplab, priyanka, suresh, mita, binod] = users;
  console.log(`✅ Created ${users.length} users`);

  // ─── PROPERTIES ─────────────────────────────────────────
  const properties = await Property.insertMany([
    {
      title: 'Spacious PG for Boys near Gauhati University',
      description: 'Well-maintained boys PG in the heart of Jalukbari. Walking distance from Gauhati University main gate. Clean rooms with attached bathrooms. Power backup and 24/7 water supply. Friendly, experienced caretaker on premises.',
      address: { street: 'House No. 12, Jalukbari Road', locality: 'Jalukbari', city: 'Guwahati', state: 'Assam', pincode: '781014' },
      coordinates: { lat: 26.1445, lng: 91.6897 },
      propertyType: 'pg',
      rent: 6500,
      deposit: 13000,
      totalRooms: 8,
      availableBeds: 3,
      furnishing: 'furnished',
      genderPreference: 'boys',
      amenities: { wifi: true, ac: false, attachedBathroom: true, parking: true, laundry: true, powerBackup: true, food: true, waterFilter: true },
      houseRules: ['No smoking inside', 'Guests allowed till 9 PM', 'No loud music after 10 PM'],
      availableFrom: new Date('2024-01-15'),
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      ],
      owner: demoOwner._id,
      college: 'Gauhati University',
      distanceFromCollege: 0.4,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 234,
      avgRating: 4.3,
      reviewCount: 7,
      scamRiskScore: 5,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'D-Mart Supermarket', type: 'grocery', distance: '200m' },
        { name: 'Jalukbari Bus Stop', type: 'bus_stop', distance: '150m' },
        { name: 'Medical Store', type: 'pharmacy', distance: '300m' },
        { name: 'Canteen Dhaaba', type: 'restaurant', distance: '100m' },
      ],
      contactPhone: '9876543211',
      contactEmail: 'owner@campusnest.demo',
    },
    {
      title: 'Girls Hostel with Mess near AEC',
      description: 'Safe and secure girls hostel near Assam Engineering College. Fully furnished rooms with AC option. Nutritious meals provided three times a day. 24/7 CCTV surveillance and security guard. Metro-bus connectivity.',
      address: { street: 'Chandmari Main Road, Nr. AEC Gate', locality: 'Chandmari', city: 'Guwahati', state: 'Assam', pincode: '781003' },
      coordinates: { lat: 26.1567, lng: 91.7362 },
      propertyType: 'hostel',
      rent: 8000,
      deposit: 16000,
      totalRooms: 12,
      availableBeds: 4,
      furnishing: 'furnished',
      genderPreference: 'girls',
      amenities: { wifi: true, ac: true, attachedBathroom: false, parking: false, laundry: true, powerBackup: true, food: true, waterFilter: true, gym: false },
      houseRules: ['Girls only', 'Curfew 10 PM', 'No alcohol', 'ID required for visitors'],
      availableFrom: new Date('2024-02-01'),
      images: [
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
      ],
      owner: suresh._id,
      college: 'Assam Engineering College',
      distanceFromCollege: 0.6,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 187,
      avgRating: 4.5,
      reviewCount: 12,
      scamRiskScore: 2,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'AEC Metro Bus Stop', type: 'bus_stop', distance: '50m' },
        { name: 'Apollo Pharmacy', type: 'pharmacy', distance: '250m' },
        { name: 'Big Bazaar', type: 'grocery', distance: '1.2km' },
        { name: 'ZOO Road ATM', type: 'atm', distance: '800m' },
      ],
      contactPhone: '9876002001',
      contactEmail: 'suresh.deka@owner.demo',
    },
    {
      title: 'Affordable Shared Flat near Dispur',
      description: 'Comfortable shared flat in Dispur, ideal for government exam aspirants. 3-bedroom flat shared by 4-6 students. Kitchen available. Close to Dispur Last Gate bus stand. Peaceful study environment.',
      address: { street: 'Housefed Complex, Near Last Gate', locality: 'Dispur', city: 'Guwahati', state: 'Assam', pincode: '781006' },
      coordinates: { lat: 26.1341, lng: 91.7898 },
      propertyType: 'flat',
      rent: 4500,
      deposit: 9000,
      totalRooms: 3,
      availableBeds: 2,
      furnishing: 'semi-furnished',
      genderPreference: 'boys',
      amenities: { wifi: true, ac: false, attachedBathroom: false, parking: true, laundry: false, powerBackup: false, food: false },
      houseRules: ['No parties', 'Shared cooking only', 'Clean common areas'],
      availableFrom: new Date('2024-01-20'),
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      owner: mita._id,
      college: 'Gauhati Commerce College',
      distanceFromCollege: 1.2,
      verificationStatus: 'pending',
      isAvailable: true,
      views: 98,
      avgRating: 3.8,
      reviewCount: 4,
      scamRiskScore: 10,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'Dispur Market', type: 'grocery', distance: '400m' },
        { name: 'Last Gate Bus Stand', type: 'bus_stop', distance: '200m' },
        { name: 'State Bank ATM', type: 'atm', distance: '300m' },
      ],
      contactPhone: '9876002002',
      contactEmail: 'mita.kalita@owner.demo',
    },
    {
      title: 'Single AC Room near Zoo Road',
      description: 'Well-furnished single room with air conditioning in a prime Zoo Road location. Ideal for students who prefer privacy. Attached bathroom, 24/7 water supply. 5 minutes walk to Zoo Road bus stop.',
      address: { street: 'Zoo Road Tiniali, Near State Zoo', locality: 'Zoo Road', city: 'Guwahati', state: 'Assam', pincode: '781005' },
      coordinates: { lat: 26.1759, lng: 91.7547 },
      propertyType: 'room',
      rent: 9500,
      deposit: 19000,
      totalRooms: 1,
      availableBeds: 1,
      furnishing: 'furnished',
      genderPreference: 'coed',
      amenities: { wifi: true, ac: true, attachedBathroom: true, parking: false, laundry: false, powerBackup: true, food: false, refrigerator: true, tv: true },
      houseRules: ['Quiet hours 11 PM-7 AM', 'No smoking'],
      availableFrom: new Date('2024-02-10'),
      images: [
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
        'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
      ],
      owner: demoOwner._id,
      college: 'Cotton University',
      distanceFromCollege: 2.1,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 156,
      avgRating: 4.6,
      reviewCount: 5,
      scamRiskScore: 3,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'Cafe Coffee Day', type: 'cafe', distance: '100m' },
        { name: 'Zoo Road Hospital', type: 'hospital', distance: '600m' },
        { name: 'Reliance Fresh', type: 'grocery', distance: '500m' },
        { name: 'Zoo Road Bus Stop', type: 'bus_stop', distance: '300m' },
      ],
      contactPhone: '9876543211',
      contactEmail: 'owner@campusnest.demo',
    },
    {
      title: 'Budget PG for Girls near Cotton University',
      description: 'Budget-friendly PG accommodation for girls near Cotton University. Shared rooms available. Clean bathrooms, good ventilation. Meals available at extra cost. Safe neighbourhood with good connectivity.',
      address: { street: 'Panbazar Lane 3, Near Cotton University', locality: 'Panbazar', city: 'Guwahati', state: 'Assam', pincode: '781001' },
      coordinates: { lat: 26.1829, lng: 91.7461 },
      propertyType: 'pg',
      rent: 4000,
      deposit: 8000,
      totalRooms: 6,
      availableBeds: 4,
      furnishing: 'semi-furnished',
      genderPreference: 'girls',
      amenities: { wifi: true, ac: false, attachedBathroom: false, parking: false, laundry: false, powerBackup: false, food: false, waterFilter: true },
      houseRules: ['Girls only', 'No male visitors inside rooms', 'Maintain cleanliness'],
      availableFrom: new Date('2024-01-25'),
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      ],
      owner: mita._id,
      college: 'Cotton University',
      distanceFromCollege: 0.3,
      verificationStatus: 'unverified',
      isAvailable: true,
      views: 67,
      avgRating: 3.5,
      reviewCount: 3,
      scamRiskScore: 20,
      scamRiskLevel: 'review_recommended',
      scamRiskFlags: ['No property photos (only 1)', 'Owner identity not verified'],
      nearbyFacilities: [
        { name: 'Panbazar Market', type: 'grocery', distance: '300m' },
        { name: 'City Bus Stop', type: 'bus_stop', distance: '200m' },
      ],
      contactPhone: '9876002002',
      contactEmail: 'mita.kalita@owner.demo',
    },
    {
      title: 'Co-ed Shared Flat in Ganeshguri',
      description: 'Modern co-ed shared flat in the popular Ganeshguri area. 2 rooms available in a 4-bedroom flat. Fully furnished. Gym, library nearby. Excellent transport links to all major colleges.',
      address: { street: 'GS Road, Ganeshguri Chowk', locality: 'Ganeshguri', city: 'Guwahati', state: 'Assam', pincode: '781005' },
      coordinates: { lat: 26.1632, lng: 91.7701 },
      propertyType: 'flat',
      rent: 7000,
      deposit: 14000,
      totalRooms: 4,
      availableBeds: 2,
      furnishing: 'furnished',
      genderPreference: 'coed',
      amenities: { wifi: true, ac: true, attachedBathroom: true, parking: true, laundry: true, powerBackup: true, food: false, gym: false, refrigerator: true },
      houseRules: ['Mutual respect', 'Shared chores roster', 'No loud parties on weekdays'],
      availableFrom: new Date('2024-02-15'),
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      ],
      owner: suresh._id,
      college: 'Assam Engineering College',
      distanceFromCollege: 3.5,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 211,
      avgRating: 4.2,
      reviewCount: 8,
      scamRiskScore: 4,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'GS Road Fitness', type: 'gym', distance: '200m' },
        { name: 'Ganeshguri Market', type: 'grocery', distance: '300m' },
        { name: 'Metro Bus Stop', type: 'bus_stop', distance: '100m' },
        { name: 'City Library', type: 'library', distance: '800m' },
        { name: 'HDFC ATM', type: 'atm', distance: '150m' },
      ],
      contactPhone: '9876002001',
      contactEmail: 'suresh.deka@owner.demo',
    },
    {
      title: 'Economy Shared Room near Jalukbari',
      description: 'Extremely affordable shared accommodation near Jalukbari flyover. Ideal for students on a tight budget. Shared bathroom, basic amenities. Bus connectivity to all major colleges.',
      address: { street: 'Jalukbari Link Road, Near Flyover', locality: 'Jalukbari', city: 'Guwahati', state: 'Assam', pincode: '781014' },
      coordinates: { lat: 26.1488, lng: 91.6812 },
      propertyType: 'shared_room',
      rent: 2500,
      deposit: 5000,
      totalRooms: 3,
      availableBeds: 3,
      furnishing: 'unfurnished',
      genderPreference: 'boys',
      amenities: { wifi: false, ac: false, attachedBathroom: false, parking: false, laundry: false, powerBackup: false, food: false },
      houseRules: ['Respect roommates', 'Shared cleaning duty'],
      availableFrom: new Date('2024-01-10'),
      images: [],
      owner: binod._id,
      college: 'Gauhati University',
      distanceFromCollege: 1.8,
      verificationStatus: 'unverified',
      isAvailable: true,
      views: 43,
      avgRating: 2.8,
      reviewCount: 2,
      scamRiskScore: 45,
      scamRiskLevel: 'high',
      scamRiskFlags: [
        'No property photos uploaded',
        'Rent significantly below area average',
        'Owner identity not verified',
        'New account (less than 7 days old)',
      ],
      nearbyFacilities: [
        { name: 'Local Store', type: 'grocery', distance: '500m' },
        { name: 'Jalukbari Bus Stop', type: 'bus_stop', distance: '600m' },
      ],
      contactPhone: '9876002003',
      contactEmail: 'binod.saikia@owner.demo',
    },
    {
      title: 'Premium Hostel near Assam Engineering College',
      description: 'State-of-the-art student hostel 5 minutes from AEC. Modern rooms with AC, dedicated study areas, high-speed WiFi. In-house canteen with South Indian, North Indian, and Chinese options. 24/7 security and CCTV.',
      address: { street: 'Jalukbari Bypass Road', locality: 'Jalukbari', city: 'Guwahati', state: 'Assam', pincode: '781014' },
      coordinates: { lat: 26.1519, lng: 91.6943 },
      propertyType: 'hostel',
      rent: 12000,
      deposit: 24000,
      totalRooms: 20,
      availableBeds: 5,
      furnishing: 'furnished',
      genderPreference: 'boys',
      amenities: { wifi: true, ac: true, attachedBathroom: true, parking: true, laundry: true, powerBackup: true, food: true, gym: true, tv: true, refrigerator: true, waterFilter: true },
      houseRules: ['No outside food in rooms', 'Study hours 8-10 PM (mandatory silence)', 'Visitors in common area only'],
      availableFrom: new Date('2024-01-01'),
      images: [
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
      ],
      owner: suresh._id,
      college: 'Assam Engineering College',
      distanceFromCollege: 0.5,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 412,
      avgRating: 4.7,
      reviewCount: 18,
      scamRiskScore: 1,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'AEC Main Canteen', type: 'restaurant', distance: '300m' },
        { name: 'Jalukbari Hospital', type: 'hospital', distance: '1km' },
        { name: 'State Bank Branch', type: 'atm', distance: '400m' },
        { name: 'Reliance Smart', type: 'grocery', distance: '700m' },
      ],
      contactPhone: '9876002001',
      contactEmail: 'suresh.deka@owner.demo',
    },
    {
      title: 'Modern 1BHK Near Gauhati Commerce College',
      description: 'Entire 1BHK flat available for single student or couple (verified). Modern kitchen, spacious bedroom, clean bathroom. Quiet residential area in Chandmari. Excellent connectivity.',
      address: { street: 'Chandmari Housing Colony, Block C', locality: 'Chandmari', city: 'Guwahati', state: 'Assam', pincode: '781003' },
      coordinates: { lat: 26.1598, lng: 91.7289 },
      propertyType: 'flat',
      rent: 11000,
      deposit: 22000,
      totalRooms: 1,
      availableBeds: 1,
      furnishing: 'furnished',
      genderPreference: 'coed',
      amenities: { wifi: true, ac: true, attachedBathroom: true, parking: true, laundry: false, powerBackup: true, food: false, refrigerator: true, tv: true, waterFilter: true },
      houseRules: ['No sub-letting', 'Maintain property'],
      availableFrom: new Date('2024-03-01'),
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
        'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
      ],
      owner: demoOwner._id,
      college: 'Gauhati Commerce College',
      distanceFromCollege: 0.8,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 89,
      avgRating: 4.4,
      reviewCount: 3,
      scamRiskScore: 4,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'Chandmari Market', type: 'grocery', distance: '300m' },
        { name: 'City Hospital', type: 'hospital', distance: '500m' },
        { name: 'ICICI ATM', type: 'atm', distance: '200m' },
        { name: 'Chai Point', type: 'cafe', distance: '100m' },
      ],
      contactPhone: '9876543211',
      contactEmail: 'owner@campusnest.demo',
    },
    {
      title: 'Cozy Room in Shared Villa - Dispur',
      description: 'Comfortable room in a shared villa near Secretariat and government offices. Perfect for UPSC / APSC aspirants. Peaceful environment, home-cooked meals available. Landlord lives on premises.',
      address: { street: 'Dispur Secretariat Road, Near Lakhimi Nagar', locality: 'Dispur', city: 'Guwahati', state: 'Assam', pincode: '781006' },
      coordinates: { lat: 26.1289, lng: 91.8002 },
      propertyType: 'room',
      rent: 5500,
      deposit: 11000,
      totalRooms: 4,
      availableBeds: 1,
      furnishing: 'semi-furnished',
      genderPreference: 'coed',
      amenities: { wifi: true, ac: false, attachedBathroom: false, parking: false, laundry: false, powerBackup: true, food: true, waterFilter: true },
      houseRules: ['Quiet study environment', 'No guests overnight'],
      availableFrom: new Date('2024-02-01'),
      images: [
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      ],
      owner: mita._id,
      college: 'Gauhati Commerce College',
      distanceFromCollege: 1.5,
      verificationStatus: 'pending',
      isAvailable: true,
      views: 134,
      avgRating: 4.1,
      reviewCount: 6,
      scamRiskScore: 15,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'Dispur Market', type: 'grocery', distance: '400m' },
        { name: 'Secretariat Bus Stop', type: 'bus_stop', distance: '150m' },
        { name: 'Dispur Library', type: 'library', distance: '300m' },
      ],
      contactPhone: '9876002002',
      contactEmail: 'mita.kalita@owner.demo',
    },
    {
      title: 'Twin-Sharing PG for Girls - Ganeshguri',
      description: 'Clean and safe twin-sharing PG for girls in Ganeshguri. Well-maintained rooms, separate bathroom for each pair. Home-cooked Assamese food twice daily. Warden available 24/7.',
      address: { street: 'Ganeshguri Colony Lane 5', locality: 'Ganeshguri', city: 'Guwahati', state: 'Assam', pincode: '781005' },
      coordinates: { lat: 26.1678, lng: 91.7789 },
      propertyType: 'pg',
      rent: 5800,
      deposit: 11600,
      totalRooms: 8,
      availableBeds: 5,
      furnishing: 'semi-furnished',
      genderPreference: 'girls',
      amenities: { wifi: true, ac: false, attachedBathroom: true, parking: false, laundry: true, powerBackup: true, food: true, waterFilter: true },
      houseRules: ['Girls only', 'Entry after 9 PM requires prior notice', 'Home food only'],
      availableFrom: new Date('2024-01-20'),
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      ],
      owner: suresh._id,
      college: 'Cotton University',
      distanceFromCollege: 2.8,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 178,
      avgRating: 4.3,
      reviewCount: 9,
      scamRiskScore: 3,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'Ganeshguri Shopping Mall', type: 'grocery', distance: '500m' },
        { name: 'Bus Stop GS Road', type: 'bus_stop', distance: '200m' },
        { name: 'Max Hospital', type: 'hospital', distance: '1.2km' },
        { name: 'StarbucksLike Cafe', type: 'cafe', distance: '400m' },
      ],
      contactPhone: '9876002001',
      contactEmail: 'suresh.deka@owner.demo',
    },
    {
      title: 'Studio Apartment for Working Students',
      description: 'Self-contained studio apartment ideal for final year or working students. Fully independent – no sharing. Private kitchen, AC, high-speed broadband. Secure building with intercom.',
      address: { street: 'GNB Road, Near RG Baruah Ground', locality: 'Zoo Road', city: 'Guwahati', state: 'Assam', pincode: '781005' },
      coordinates: { lat: 26.1812, lng: 91.7612 },
      propertyType: 'flat',
      rent: 14000,
      deposit: 28000,
      totalRooms: 1,
      availableBeds: 1,
      furnishing: 'furnished',
      genderPreference: 'coed',
      amenities: { wifi: true, ac: true, attachedBathroom: true, parking: true, laundry: false, powerBackup: true, food: false, refrigerator: true, tv: true, waterFilter: true },
      houseRules: ['Single occupancy only', 'No loud music', 'Pets allowed (small)'],
      availableFrom: new Date('2024-02-20'),
      images: [
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      ],
      owner: demoOwner._id,
      college: 'Cotton University',
      distanceFromCollege: 3.2,
      verificationStatus: 'verified',
      isAvailable: true,
      views: 95,
      avgRating: 4.8,
      reviewCount: 4,
      scamRiskScore: 2,
      scamRiskLevel: 'low',
      scamRiskFlags: [],
      nearbyFacilities: [
        { name: 'GNB Road Gym', type: 'gym', distance: '100m' },
        { name: 'Guwahati Railway Station', type: 'metro_station', distance: '2.5km' },
        { name: 'Vishal Mega Mart', type: 'grocery', distance: '600m' },
        { name: 'GNRC Hospital', type: 'hospital', distance: '1km' },
        { name: 'SBI ATM', type: 'atm', distance: '300m' },
      ],
      contactPhone: '9876543211',
      contactEmail: 'owner@campusnest.demo',
    },
  ]);

  console.log(`✅ Created ${properties.length} properties`);

  // ─── ROOMMATE PROFILES ───────────────────────────────────
  const roommateProfiles = await RoommateProfile.insertMany([
    {
      user: demoStudent._id,
      name: 'Priya Sharma',
      college: 'Gauhati University',
      budget: { min: 4000, max: 8000 },
      preferredLocality: 'Jalukbari',
      moveInDate: new Date('2024-02-01'),
      roomType: 'pg',
      genderPreference: 'female',
      sleepSchedule: 'early_bird',
      studyHabits: 'quiet',
      cleanliness: 'very_clean',
      smoking: false,
      drinking: false,
      foodPreference: 'veg',
      noiseTolerance: 'low',
      visitors: 'occasional',
      pets: false,
      bio: 'Final year BSc student. Love reading and quiet evenings. Looking for a clean, focused roommate.',
      isActive: true,
    },
    {
      user: ankita._id,
      name: 'Ankita Das',
      college: 'Assam Engineering College',
      budget: { min: 5000, max: 10000 },
      preferredLocality: 'Chandmari',
      moveInDate: new Date('2024-02-15'),
      roomType: 'flat',
      genderPreference: 'female',
      sleepSchedule: 'night_owl',
      studyHabits: 'with_music',
      cleanliness: 'clean',
      smoking: false,
      drinking: false,
      foodPreference: 'any',
      noiseTolerance: 'medium',
      visitors: 'occasional',
      pets: false,
      bio: 'CSE student at AEC. Night coder! Looking for a chill flatmate who respects personal space.',
      isActive: true,
    },
    {
      user: rohan._id,
      name: 'Rohan Borah',
      college: 'Cotton University',
      budget: { min: 3000, max: 6000 },
      preferredLocality: 'Ganeshguri',
      moveInDate: new Date('2024-03-01'),
      roomType: 'shared_room',
      genderPreference: 'male',
      sleepSchedule: 'flexible',
      studyHabits: 'social',
      cleanliness: 'moderate',
      smoking: false,
      drinking: true,
      foodPreference: 'non_veg',
      noiseTolerance: 'high',
      visitors: 'frequent',
      pets: true,
      bio: 'Arts student who loves football and music. Looking for fun flatmates.',
      isActive: true,
    },
    {
      user: meenakshi._id,
      name: 'Meenakshi Gogoi',
      college: 'Gauhati Commerce College',
      budget: { min: 4000, max: 7000 },
      preferredLocality: 'Dispur',
      moveInDate: new Date('2024-02-01'),
      roomType: 'pg',
      genderPreference: 'female',
      sleepSchedule: 'early_bird',
      studyHabits: 'quiet',
      cleanliness: 'clean',
      smoking: false,
      drinking: false,
      foodPreference: 'veg',
      noiseTolerance: 'low',
      visitors: 'never',
      pets: false,
      bio: 'Commerce student preparing for CA. Need a quiet, focused environment.',
      isActive: true,
    },
    {
      user: biplab._id,
      name: 'Biplab Nath',
      college: 'Assam Engineering College',
      budget: { min: 6000, max: 12000 },
      preferredLocality: 'Jalukbari',
      moveInDate: new Date('2024-01-20'),
      roomType: 'flat',
      genderPreference: 'male',
      sleepSchedule: 'night_owl',
      studyHabits: 'with_music',
      cleanliness: 'clean',
      smoking: false,
      drinking: true,
      foodPreference: 'non_veg',
      noiseTolerance: 'medium',
      visitors: 'occasional',
      pets: false,
      bio: 'Mechanical engineer student. Love cooking and cricket. Easy-going flatmate.',
      isActive: true,
    },
    {
      user: priyanka._id,
      name: 'Priyanka Baruah',
      college: 'Gauhati University',
      budget: { min: 5000, max: 9000 },
      preferredLocality: 'Zoo Road',
      moveInDate: new Date('2024-03-01'),
      roomType: 'pg',
      genderPreference: 'female',
      sleepSchedule: 'flexible',
      studyHabits: 'flexible',
      cleanliness: 'very_clean',
      smoking: false,
      drinking: false,
      foodPreference: 'veg',
      noiseTolerance: 'medium',
      visitors: 'occasional',
      pets: true,
      bio: 'Mass comm student. Love art, chai, and good conversations. Pet-friendly space preferred.',
      isActive: true,
    },
    // 2 extra profiles for seed diversity
    {
      user: suresh._id,
      name: 'Suresh Deka',
      college: 'Gauhati University',
      budget: { min: 3000, max: 5000 },
      preferredLocality: 'Jalukbari',
      moveInDate: new Date('2024-02-10'),
      roomType: 'shared_room',
      genderPreference: 'male',
      sleepSchedule: 'early_bird',
      studyHabits: 'quiet',
      cleanliness: 'moderate',
      smoking: false,
      drinking: false,
      foodPreference: 'any',
      noiseTolerance: 'medium',
      visitors: 'occasional',
      pets: false,
      bio: 'Working part time. Need a budget room, easy-going.',
      isActive: true,
    },
    {
      user: mita._id,
      name: 'Mita Kalita',
      college: 'Cotton University',
      budget: { min: 4500, max: 8500 },
      preferredLocality: 'Chandmari',
      moveInDate: new Date('2024-02-20'),
      roomType: 'pg',
      genderPreference: 'female',
      sleepSchedule: 'early_bird',
      studyHabits: 'quiet',
      cleanliness: 'clean',
      smoking: false,
      drinking: false,
      foodPreference: 'veg',
      noiseTolerance: 'low',
      visitors: 'occasional',
      pets: false,
      bio: 'English Hons student. Bookworm and occasional baker. Prefer a calm household.',
      isActive: true,
    },
  ]);
  console.log(`✅ Created ${roommateProfiles.length} roommate profiles`);

  // ─── REVIEWS ────────────────────────────────────────────
  const [prop1, prop2, prop3, prop4, , prop6, , prop8] = properties;

  const reviews = await Review.insertMany([
    {
      property: prop1._id,
      student: ankita._id,
      ratings: { roomQuality: 4, locality: 5, water: 4, electricity: 5, internet: 4, ownerBehaviour: 5, safety: 5, valueForMoney: 4 },
      overallRating: 5,
      comment: 'Excellent PG! Very close to university, owner is very helpful. Water supply is consistent. Would highly recommend to GU students.',
    },
    {
      property: prop1._id,
      student: meenakshi._id,
      ratings: { roomQuality: 4, locality: 4, water: 4, electricity: 4, internet: 3, ownerBehaviour: 4, safety: 4, valueForMoney: 4 },
      overallRating: 4,
      comment: 'Good PG overall. WiFi could be faster but other facilities are great. The food is homely and tasty.',
    },
    {
      property: prop2._id,
      student: priyanka._id,
      ratings: { roomQuality: 5, locality: 4, water: 5, electricity: 5, internet: 5, ownerBehaviour: 5, safety: 5, valueForMoney: 4 },
      overallRating: 5,
      comment: 'Best hostel near AEC! Security is top-notch, staff is helpful. The mess food is surprisingly good. AC rooms are worth the extra cost.',
    },
    {
      property: prop3._id,
      student: biplab._id,
      ratings: { roomQuality: 3, locality: 4, water: 4, electricity: 3, internet: 4, ownerBehaviour: 4, safety: 3, valueForMoney: 4 },
      overallRating: 4,
      comment: 'Decent budget flat. Very affordable. Power cuts occasionally but manageable. Good for students who just need a place to sleep.',
    },
    {
      property: prop4._id,
      student: rohan._id,
      ratings: { roomQuality: 5, locality: 5, water: 5, electricity: 5, internet: 5, ownerBehaviour: 5, safety: 5, valueForMoney: 4 },
      overallRating: 5,
      comment: 'Amazing room! AC, attached bathroom, perfect for focused studying. Zoo Road location is super convenient. A bit pricey but worth it.',
    },
    {
      property: prop6._id,
      student: demoStudent._id,
      ratings: { roomQuality: 4, locality: 4, water: 4, electricity: 4, internet: 5, ownerBehaviour: 4, safety: 4, valueForMoney: 3 },
      overallRating: 4,
      comment: 'Lovely co-ed flat in Ganeshguri. Flatmates are friendly. Transport connectivity is excellent. The only downside is no food included.',
    },
    {
      property: prop8._id,
      student: ankita._id,
      ratings: { roomQuality: 5, locality: 4, water: 5, electricity: 5, internet: 5, ownerBehaviour: 5, safety: 5, valueForMoney: 3 },
      overallRating: 5,
      comment: 'The premium hostel near AEC is excellent! Study rooms are great, gym is a bonus. Expensive but very professional management.',
    },
    {
      property: prop8._id,
      student: biplab._id,
      ratings: { roomQuality: 5, locality: 5, water: 5, electricity: 5, internet: 5, ownerBehaviour: 4, safety: 5, valueForMoney: 4 },
      overallRating: 5,
      comment: 'Best hostel experience. Very clean, well-managed, food is great. Highly recommended for AEC students.',
    },
    {
      property: prop2._id,
      student: meenakshi._id,
      ratings: { roomQuality: 4, locality: 5, water: 4, electricity: 4, internet: 4, ownerBehaviour: 5, safety: 5, valueForMoney: 4 },
      overallRating: 4,
      comment: 'Safe and secure girls hostel. Very convenient for AEC. The curfew is strict but understandable for safety.',
    },
    {
      property: prop3._id,
      student: rohan._id,
      ratings: { roomQuality: 3, locality: 4, water: 3, electricity: 3, internet: 4, ownerBehaviour: 3, safety: 3, valueForMoney: 5 },
      overallRating: 3,
      comment: 'Very cheap accommodation. No AC or attached bathroom but excellent value for money if you are on a budget.',
    },
  ]);
  console.log(`✅ Created ${reviews.length} reviews`);

  // ─── ENQUIRIES ───────────────────────────────────────────
  await Enquiry.insertMany([
    {
      property: prop1._id,
      student: demoStudent._id,
      owner: demoOwner._id,
      studentName: 'Priya Sharma',
      contactNumber: '9876543210',
      preferredVisitDate: new Date('2024-02-05'),
      moveInDate: new Date('2024-02-15'),
      message: 'Hi, I am a 3rd year BSc student at GU. I am interested in the PG near university. Is the room still available? Can I visit this weekend?',
      status: 'responded',
      ownerResponse: 'Yes, the room is available. Please come on Saturday 11 AM. Call me before you arrive.',
    },
    {
      property: prop2._id,
      student: ankita._id,
      owner: suresh._id,
      studentName: 'Ankita Das',
      contactNumber: '9876001001',
      preferredVisitDate: new Date('2024-02-08'),
      moveInDate: new Date('2024-02-20'),
      message: 'I am an AEC student looking for girls hostel. Is the AC room available? What are the mess timings?',
      status: 'seen',
    },
    {
      property: prop4._id,
      student: rohan._id,
      owner: demoOwner._id,
      studentName: 'Rohan Borah',
      contactNumber: '9876001002',
      preferredVisitDate: new Date('2024-02-10'),
      moveInDate: new Date('2024-03-01'),
      message: 'Looking for the AC room near Zoo Road. Cotton Uni student. Can I negotiate the deposit?',
      status: 'pending',
    },
  ]);
  console.log('✅ Created enquiries');

  // ─── REPORTS ────────────────────────────────────────────
  await Report.insertMany([
    {
      property: properties[6]._id, // High risk property
      reportedBy: demoStudent._id,
      reason: 'fake_listing',
      description: 'The owner is asking for advance payment before showing the property. This looks like a scam. The rent is also unrealistically low for this area.',
      status: 'pending',
    },
    {
      property: properties[6]._id,
      reportedBy: ankita._id,
      reason: 'advance_payment',
      description: 'Owner called and asked for ₹10,000 advance via UPI before confirming visit slot. This is suspicious behaviour.',
      status: 'pending',
    },
    {
      property: properties[4]._id, // Unverified budget PG
      reportedBy: meenakshi._id,
      reason: 'wrong_info',
      description: 'The listing shows WiFi available but the actual property does not have working internet. The photos also do not match the actual rooms.',
      status: 'reviewed',
      adminNotes: 'Owner contacted. Photos to be updated.',
    },
  ]);
  console.log('✅ Created reports');

  console.log('\n🎉 Seed completed successfully!');
  console.log('─────────────────────────────────');
  console.log('Demo Accounts:');
  console.log('  Student → student@campusnest.demo / Demo@123');
  console.log('  Owner   → owner@campusnest.demo / Demo@123');
  console.log('  Admin   → admin@campusnest.demo / Demo@123');
  console.log('─────────────────────────────────');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
